-- =============================================
-- 핸디즈 인원관리 플랫폼 - Seed Data
-- 기존 스프레드싘트 데이터 기반 자동 생성
-- migration.sql 실행 후 이 파일을 실행하세요
-- =============================================

INSERT INTO employees (name, eng_name, email, branch_id, status, slot_number, is_hm, status_note) VALUES
  ('Dater', 'Dater', NULL, 1, 'active', 1, FALSE, ''),
  ('채용필요', 'Hiring', NULL, 1, 'hiring', 2, FALSE, '주디(3/16 이동)'),
  ('채용필요', 'Hiring', NULL, 1, 'hiring', 3, FALSE, '줄리엔(3/22퇴사예정)'),
  ('권바다', 'Moana', 'moana.kwon@handys.co.kr', 2, 'active', 1, FALSE, ''),
  ('빉스', 'Vix', NULL, 2, 'active', 2, FALSE, ''),
  ('김도연', 'Goose', 'goose.kim@handys.co.kr', 2, 'active', 3, FALSE, ''),
  ('아런', 'Arun', NULL, 2, 'active', 4, FALSE, '8/4'),
  ('사고', 'Sago', NULL, 3, 'active', 1, FALSE, ''),
  ('힐다', 'Hilda', NULL, 3, 'active', 2, FALSE, ''),
  ('패미', 'Fami', NULL, 3, 'active', 3, FALSE, '10/27'),
  ('채용필요', 'Hiring', NULL, 3, 'hiring', 4, FALSE, '채용 요청O'),
  ('카밀리', 'Camili', NULL, 4, 'active', 1, FALSE, ''),
  ('사니', 'Sani', NULL, 4, 'active', 2, FALSE, ''),
  ('채용필요', 'Hiring', NULL, 4, 'hiring', 3, FALSE, '채용 요청O'),
  ('오렌', 'Oren', NULL, 5, 'transfer', 1, FALSE, '3/23 이동'),
  ('폼', 'Pom', NULL, 5, 'active', 2, FALSE, ''),
  ('윈디', 'Windy', NULL, 5, 'transfer', 3, FALSE, '3/23 이동'),
  ('하이', 'Hi', NULL, 5, 'active', 4, FALSE, ''),
  ('이즈', 'Iz', NULL, 5, 'active', 5, FALSE, '8/4'),
  ('김유진', 'Yulia', 'yulia.kim@handys.co.kr', 5, 'active', 6, FALSE, '9/15'),
  ('김예릸', 'Bono', 'bono.kim@handys.co.kr', 6, 'active', 1, FALSE, ''),
  ('엘사', 'Elsa', NULL, 6, 'active', 2, FALSE, ''),
  ('김정연', 'Kali', 'kali.kim@handys.co.kr', 6, 'active', 3, FALSE, ''),
  ('니코', 'Nico', NULL, 6, 'active', 4, FALSE, '7/7'),
  ('강태욱', 'Dawson', 'dawson.kang@handys.co.kr', 6, 'active', 5, FALSE, '11/3'),
  ('채용필요', 'Hiring', NULL, 6, 'hiring', 6, FALSE, '틬카 퇴사 2/15'),
  ('메인', 'Main', NULL, 7, 'active', 1, FALSE, ''),
  ('김정재', 'Asher', 'asher.kim@handys.co.kr', 7, 'active', 2, FALSE, '12/1'),
  ('지오', 'Gio', NULL, 7, 'active', 3, FALSE, '3/16'),
  ('매런', 'Maren', NULL, 7, 'active', 4, FALSE, '1/5'),
  ('카이', 'Kai', NULL, 7, 'active', 5, FALSE, '1/5'),
  ('권동혘', 'Roy', 'roy.kwon@handys.co.kr', 8, 'transfer', 1, FALSE, '4/1 이동'),
  ('오스카', 'Oscar', NULL, 8, 'active', 2, FALSE, '9/15'),
  ('밸레나', 'Vallena', NULL, 8, 'active', 3, FALSE, '1/19'),
  ('피아', 'Pia', NULL, 8, 'active', 4, FALSE, '3/16'),
  ('헤일리', 'Hailey', NULL, 9, 'active', 1, FALSE, ''),
  ('칸', 'Khan', NULL, 9, 'active', 2, FALSE, ''),
  ('카라', 'Kara', NULL, 9, 'active', 3, FALSE, ''),
  ('에드', 'Ed', NULL, 9, 'onboarding', 4, FALSE, '4/6 입사'),
  ('조이', 'Joy', NULL, 9, 'active', 5, FALSE, '8/4'),
  ('버디', 'Buddy', NULL, 9, 'active', 6, FALSE, '9/15'),
  ('루미', 'Rumi', NULL, 9, 'active', 7, FALSE, '10/27'),
  ('나탈리', 'Natalie', NULL, 9, 'active', 8, FALSE, '12/01'),
  ('푼나', 'Puna', NULL, 10, 'active', 1, FALSE, ''),
  ('아이엔', 'Ian', NULL, 10, 'active', 2, FALSE, ''),
  ('리아', 'Ria', NULL, 10, 'active', 3, FALSE, ''),
  ('오스틴', 'Austin', NULL, 10, 'active', 4, FALSE, ''),
  ('진', 'Jin', NULL, 11, 'active', 1, FALSE, ''),
  ('시아', 'Sia', NULL, 11, 'active', 2, FALSE, ''),
  ('맥스', 'Max', NULL, 11, 'active', 3, FALSE, ''),
  ('아이', 'Ai', NULL, 11, 'onboarding', 4, FALSE, '4/6 입사'),
  ('에린', 'Erin', NULL, 11, 'active', 5, FALSE, '8/4'),
  ('셀럭', 'Celuck', NULL, 11, 'active', 6, FALSE, '9/15'),
  ('삨', 'Shan', NULL, 12, 'active', 1, FALSE, ''),
  ('김수연', 'Beth', 'beth.kim@handys.co.kr', 12, 'active', 2, FALSE, ''),
  ('알팍산더', 'Alexander', NULL, 12, 'active', 3, FALSE, ''),
  ('하니', 'Hani', NULL, 12, 'active', 4, FALSE, '12/01'),
  ('테리', 'Terry', NULL, 12, 'active', 5, FALSE, ''),
  ('이비', 'Ivy', NULL, 13, 'active', 1, FALSE, ''),
  ('아이번', 'Ivan', NULL, 13, 'active', 2, FALSE, ''),
  ('김완주', 'Caesar', 'caesar.kim@handys.co.kr', 13, 'active', 3, FALSE, ''),
  ('브루스', 'Bruce', NULL, 13, 'active', 4, FALSE, ''),
  ('라빈', 'Rabin', NULL, 14, 'active', 1, FALSE, ''),
  ('칸', 'Khan', NULL, 14, 'active', 2, FALSE, ''),
  ('김나영', 'Aria', 'aria.kim@handys.co.kr', 14, 'active', 3, FALSE, ''),
  ('강예진', 'Vivian', 'vivian.kang@handys.co.kr', 15, 'active', 1, FALSE, ''),
  ('곽여진', 'Maisie', 'maisie.kwak@handys.co.kr', 15, 'active', 2, FALSE, ''),
  ('필리', 'Philly', NULL, 15, 'active', 3, FALSE, ''),
  ('호치', 'Hochi', NULL, 15, 'active', 4, FALSE, '5/26'),
  ('채용필요', 'Hiring', NULL, 16, 'hiring', 1, FALSE, '새 2월말 퇴사'),
  ('리즈', 'Liz', NULL, 16, 'active', 2, FALSE, ''),
  ('디이', 'Dee', NULL, 17, 'active', 1, FALSE, ''),
  ('다니엘', 'Daniel', NULL, 17, 'active', 2, FALSE, ''),
  ('김서윤', 'Yuni', 'yuni.kim@handys.co.kr', 17, 'active', 3, FALSE, ''),
  ('테드', 'Ted', NULL, 17, 'active', 4, FALSE, ''),
  ('제나', 'Jena', NULL, 17, 'active', 5, FALSE, ''),
  ('바스', 'Basil', NULL, 17, 'active', 6, FALSE, ''),
  ('래이', 'Ray', NULL, 17, 'active', 7, FALSE, '3/16'),
  ('위니', 'Winnie', NULL, 18, 'active', 1, FALSE, ''),
  ('김수연', 'Sophie', 'sophie.kim@handys.co.kr', 18, 'active', 2, FALSE, '10/27'),
  ('앨리', 'Ally', NULL, 18, 'active', 3, FALSE, '11/3'),
  ('푸디', 'Foody', NULL, 18, 'active', 4, FALSE, '12/15'),
  ('에드워드', 'Edward', NULL, 19, 'active', 1, FALSE, ''),
  ('레니', 'Reni', NULL, 19, 'active', 2, FALSE, ''),
  ('다프네', 'Daphne', NULL, 19, 'active', 3, FALSE, ''),
  ('김슬아', 'Aki', 'aki.kim@handys.co.kr', 19, 'active', 4, FALSE, '8/4'),
  ('저니', 'Journey', NULL, 20, 'active', 1, FALSE, ''),
  ('모나', 'Mona', NULL, 20, 'active', 2, FALSE, ''),
  ('라일', 'Ryle', NULL, 20, 'active', 3, FALSE, ''),
  ('패나', 'Pana', NULL, 20, 'active', 4, FALSE, ''),
  ('소피아', 'Sophia', NULL, 21, 'active', 1, FALSE, ''),
  ('조이스', 'Joyce', NULL, 21, 'active', 2, FALSE, '10/27'),
  ('스카이', 'Sky', NULL, 21, 'active', 3, FALSE, '10/27'),
  ('제니', 'Jenny', NULL, 22, 'active', 1, FALSE, ''),
  ('대론', 'Daron', NULL, 22, 'active', 2, FALSE, '11/17'),
  ('아이비', 'Ivy2', NULL, 22, 'active', 3, FALSE, '12/01'),
  ('버드', 'Bird', NULL, 22, 'active', 4, FALSE, '1/19 (아이자 육휴)'),
  ('엘리', 'Elly', NULL, 23, 'transfer', 1, FALSE, '4/1 이동'),
  ('사사', 'Sasa', NULL, 23, 'active', 2, FALSE, ''),
  ('마린', 'Marine', NULL, 23, 'active', 3, FALSE, '2/2'),
  ('Luan', 'Luan', NULL, 23, 'active', 4, FALSE, '2/23'),
  ('제레미', 'Jeremy', NULL, 24, 'active', 1, FALSE, ''),
  ('세나', 'Sena', NULL, 24, 'active', 2, FALSE, ''),
  ('코디', 'Cody', NULL, 24, 'active', 3, FALSE, '1/1'),
  ('리안', 'Rian', NULL, 25, 'active', 1, FALSE, '3/16'),
  ('고혜인', 'Marie', 'marie.go@handys.co.kr', 25, 'active', 2, FALSE, ''),
  ('김민주', 'Kassy', 'kassy.kim@handys.co.kr', 25, 'active', 3, FALSE, ''),
  ('제이크', 'Jake', NULL, 25, 'active', 4, FALSE, '1/19'),
  ('Daisy', 'Daisy', NULL, 1, 'active', NULL, TRUE, 'HM'),
  ('루시', '루시', NULL, 2, 'active', NULL, TRUE, 'HM'),
  ('리알', '리알', NULL, 3, 'active', NULL, TRUE, 'HM'),
  ('젬', '젬', NULL, 4, 'active', NULL, TRUE, 'HM'),
  ('이나', '이나', NULL, 5, 'active', NULL, TRUE, 'HM'),
  ('제리', '제리', NULL, 6, 'active', NULL, TRUE, 'HM'),
  ('해닉', '해닉', NULL, 7, 'active', NULL, TRUE, 'HM'),
  ('지안', '지안', NULL, 8, 'active', NULL, TRUE, 'HM'),
  ('맥', '맥', NULL, 9, 'active', NULL, TRUE, 'HM'),
  ('조셉', '조셉', NULL, 10, 'active', NULL, TRUE, 'HM'),
  ('웰컴', '웰컴', NULL, 11, 'active', NULL, TRUE, 'HM'),
  ('레오', '레오', NULL, 12, 'active', NULL, TRUE, 'HM'),
  ('스텐', '스텐', NULL, 13, 'active', NULL, TRUE, 'HM'),
  ('써니', '써니', NULL, 14, 'active', NULL, TRUE, 'HM'),
  ('테디', '테디', NULL, 15, 'active', NULL, TRUE, 'HM'),
  ('우디', '우디', NULL, 16, 'active', NULL, TRUE, 'HM'),
  ('스칼렛', '스칼렛', NULL, 17, 'active', NULL, TRUE, 'HM'),
  ('클레어', '클레어', NULL, 18, 'active', NULL, TRUE, 'HM'),
  ('셸머', '셸머', NULL, 19, 'active', NULL, TRUE, 'HM'),
  ('엠제이', '엠제이', NULL, 20, 'active', NULL, TRUE, 'HM'),
  ('로드', '로드', NULL, 21, 'active', NULL, TRUE, 'HM'),
  ('원스턴', '원스턴', NULL, 22, 'active', NULL, TRUE, 'HM'),
  ('제이미', '제이미', NULL, 23, 'active', NULL, TRUE, 'HM'),
  ('카터', '카터', NULL, 24, 'active', NULL, TRUE, 'HM'),
  ('카밀', '카밀', NULL, 25, 'active', NULL, TRUE, 'HM'),
  ('강지혜', 'Lily', 'lily.kang@handys.co.kr', 15, 'active', NULL, FALSE, ''),
  ('고경진', 'Eiden', 'eiden.go@handys.co.kr', 27, 'active', NULL, FALSE, ''),
  ('고경하', 'Zenia', 'zenia.go@handys.co.kr', 12, 'active', NULL, FALSE, ''),
  ('곽태범', 'Owen', 'owen.kwak@handys.co.kr', 5, 'active', NULL, FALSE, ''),
  ('권상희', 'Jarry', 'jarry.kwon@handys.co.kr', 6, 'active', NULL, FALSE, ''),
  ('권초찬', 'Victor', 'victor.kwon@handys.co.kr', 11, 'active', NULL, FALSE, ''),
  ('김다애', 'Diana', 'diana.kim@handys.co.kr', NULL, 'active', NULL, FALSE, ''),
  ('김다정', 'Riley', 'riley.kim@handys.co.kr', 26, 'active', NULL, FALSE, ''),
  ('김대목', 'Woody', 'woody.kim@handys.co.kr', 16, 'active', NULL, FALSE, ''),
  ('김서연', 'Blair', 'blair.kim@handys.co.kr', 26, 'active', NULL, FALSE, ''),
  ('김선진', 'Zoe', 'zoe.kim@handys.co.kr', 9, 'active', NULL, FALSE, ''),
  ('김정이', 'Tessa', 'tessa.kim@handys.co.kr', NULL, 'active', NULL, FALSE, '');

-- 총 145명 INSERT

-- Stats: 145 with email, 0 without email (nickname only)
